services:
  garage:
    image: dxflrs/garage:v1.0.1
    ports:
      - "3900:3900"
      - "3903:3903"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage_data:/data

volumes:
  garage_data:
